# Generated by Django 3.1.5 on 2021-01-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cena',
            field=models.FloatField(),
        ),
    ]
