# Generated by Django 3.1.5 on 2021-01-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0002_auto_20210124_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='przecena',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='nazwa',
            field=models.CharField(max_length=120),
        ),
    ]
