# Generated by Django 3.1.5 on 2021-01-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0003_auto_20210124_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='przecena',
            field=models.BooleanField(default=False),
        ),
    ]
