# Generated by Django 3.1.5 on 2021-01-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0004_auto_20210126_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='deskaJesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('zdjecie', models.ImageField(upload_to='')),
                ('opis', models.TextField()),
                ('cena', models.FloatField()),
                ('przecena', models.BooleanField(default=False)),
                ('ilosc', models.FloatField()),
            ],
        ),
    ]
