# Generated by Django 3.1.5 on 2021-01-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0005_deskajesion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deskaJesion',
        ),
    ]
