# Generated by Django 3.1.5 on 2021-01-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0007_kategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name_plural': 'kategorie'},
        ),
        migrations.AddField(
            model_name='product',
            name='kategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produkty.kategoria'),
            preserve_default=False,
        ),
    ]
