# Generated by Django 3.1.5 on 2021-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0011_product_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='zdjecie',
            field=models.ImageField(upload_to='fotki'),
        ),
    ]
