# Generated by Django 3.1.5 on 2021-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0013_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
