# Generated by Django 3.1.5 on 2021-01-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0014_auto_20210130_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
