# Generated by Django 3.1.5 on 2021-01-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0015_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
