# Generated by Django 3.1.5 on 2021-01-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0016_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
