# Generated by Django 3.1.5 on 2021-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0018_product_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('nazwa', 'slug')},
        ),
    ]
