# Generated by Django 3.1.5 on 2021-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0022_auto_20210205_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo9',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.TextField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
