# Generated by Django 3.1.5 on 2021-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0023_auto_20210206_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo7',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo8',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo9',
            field=models.ImageField(blank=True, upload_to='portfolioImages'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
