# Generated by Django 3.1.5 on 2021-02-01 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0019_auto_20210130_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20210201_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rzeczy',
            field=models.ManyToManyField(blank=True, to='produkty.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
