# Generated by Django 3.1.5 on 2021-02-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0019_auto_20210130_1437'),
        ('account', '0006_auto_20210201_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzeczyWKoszu', models.ManyToManyField(blank=True, to='produkty.Product')),
            ],
        ),
    ]
