# Generated by Django 3.1.5 on 2021-02-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_koszyk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Koszyk',
        ),
    ]
