# Generated by Django 3.1.5 on 2021-02-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0019_auto_20210130_1437'),
        ('account', '0012_auto_20210201_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rzeczyWKoszu',
            field=models.ManyToManyField(null=True, to='produkty.Product'),
        ),
    ]
